#!/bin/sh
[ -n "$1" ] && HOFF="$1" || HOFF=400
mocp -i | awk '{
    if ($0!~/^Status: STOP:/) { ss="true" };
    if ($1~/^TotalSec:/) { ts=$2 };
    if ($1~/^CurrentSec:/) { cs=$2 };
} END {
    if (ss!~/true/) {print int(cs/(ts/100))} else {print "0"}
}'
